version: '3'

services: 
    db:
        image: postgres:10.1
        volumes:
            - postgres_data:/var/lib/postgresql/data
    web:
        build: .
        command: python /code/manage.py migrate --noinput
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DJANGO_SETTINGS_MODULE=tweetme.settings.production
            - SECRET_KEY=iw9ngy@z6yz6d6lrx4j3sdyf015q18%f5rl+#d+#cr*rcqha29
volumes:
    postgres_data:
